import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("career page contains the required positioning and accessible disclosure controls", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const layout = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");

  assert.match(page, /Chelsea Shen/);
  assert.doesNotMatch(page, /沈 川/);
  assert.doesNotMatch(page, /<em>沈 川<\/em>/);
  assert.match(page, /<p className="eyebrow">PROFILE<\/p>/);
  assert.doesNotMatch(page, /<nav aria-label="页面导航">/);
  assert.doesNotMatch(page, /<a href="#profile">简介<\/a>/);
  assert.doesNotMatch(page, /<a href="#experience">经历<\/a>/);
  assert.match(page, /数字化转型与产品落地交付/);
  assert.match(page, /连接业务、数据与技术，推动品牌数字化转型及数据产品交付，驱动广告、会员、线下零售等业务运营优化/);
  assert.match(page, /工作理念：沉下心，有担当，有热爱/);
  assert.doesNotMatch(page, /工作理念：能担当，有热爱，沉下心把专业做透/);
  assert.doesNotMatch(page, /浏览工作经历/);
  assert.doesNotMatch(page, /负责、热爱/);
  assert.doesNotMatch(page, /聚焦奢侈品、美妆、汽车及酒店行业的数据与客户运营场景/);
  assert.match(page, /6\+<\/strong><span>年工作经验/);
  assert.match(page, /墨尔本大学<\/strong><span>市场营销与分析（本\/硕）/);
  assert.doesNotMatch(page, /本科、硕士｜市场营销与分析/);
  assert.doesNotMatch(page, /个硕博学位/);
  assert.match(page, /<div className="hero-copy">[\s\S]*<div className="fact-grid" aria-label="职业与教育概览">/);
  assert.doesNotMatch(page, /<aside className="hero-facts"/);
  assert.match(page, /<h2 id="profile-title">端到端的产品解决方案交付<\/h2>/);
  assert.match(page, /<p className="profile-subtitle">产品规划，产品落地，业务赋能<\/p>/);
  assert.match(page, /识别业务机会，定义 Use Case，制定优先级与路线图<\/p>/);
  assert.match(page, /以 PM \/ BA 身份连接业务、数据与技术，推进端到端交付<\/p>/);
  assert.match(page, /将用户、营销与经营数据转化为可执行的增长和运营策略<\/p>/);
  assert.doesNotMatch(page, /识别业务机会，定义 Use Case，制定优先级与路线图。/);
  assert.doesNotMatch(page, /以 PM \/ BA 身份连接业务、数据与技术，推进端到端交付。/);
  assert.doesNotMatch(page, /将用户、营销与经营数据转化为可执行的增长和运营策略。/);
  assert.doesNotMatch(page, /产品规划 &gt; 产品落地 &gt; 业务赋能/);
  assert.doesNotMatch(page, /端到端的产品解决方案交付（/);
  assert.doesNotMatch(page, /亮点：交付端到端的产品解决方案/);
  assert.doesNotMatch(page, /经历亮点：端到端的产品解决方案/);
  assert.doesNotMatch(page, /01 \/ Profile/);
  assert.doesNotMatch(page, /把模糊的业务问题，变成可落地的数据与产品方案/);
  assert.doesNotMatch(page, /具备从需求洞察、Use Case 规划、数据分析与产品设计/);
  assert.doesNotMatch(page, /从业务机会识别、路线图制定，到数据产品设计、开发协同及上线运营的端到端交付/);
  assert.doesNotMatch(page, /从用户分层、行为路径与外部数据机会中提炼策略，推动营销、CRM 与商品运营决策/);
  assert.doesNotMatch(page, /<p className="employer-overview">/);
  assert.doesNotMatch(page, /面向集团管理层、办公室团队与门店，建立统一的经营、客户、商品及门店数据决策支持。/);
  assert.doesNotMatch(page, /从 0 到 1 规划、实施并运营营销数据平台，打通全域投放数据与业务决策场景。/);
  assert.match(page, /面向 Marketing、E-commerce、CRM、Merchandising 及 Retail 团队梳理未来 3–5 年业务需求与痛点，沉淀跨部门 Use Case 清单、价值评估框架及实施路线图"/);
  assert.doesNotMatch(page, /面向 Marketing、E-commerce、CRM、Merchandising 及 Retail 团队梳理未来 3–5 年业务需求与痛点，沉淀跨部门 Use Case 清单、价值评估框架及实施路线图。/);
  assert.doesNotMatch(page, /运营迭代机制。/);
  assert.doesNotMatch(page, /商品规划决策。/);
  assert.match(page, /aria-expanded/);
  assert.match(page, /aria-controls/);
  assert.match(page, /useState\(""\)/);
  assert.doesNotMatch(page, /useState\("deloitte"\)/);
  assert.match(page, /useState<Record<string, boolean>>\(\{\}\)/);
  assert.match(page, /阶段 1｜三年期产品规划/);
  assert.match(page, /阶段 2｜一期产品实施/);
  assert.match(page, /基于广告投放业务需求，制定三年期产品规划方案，设计分阶段业务 Use Case 及实施路线图/);
  assert.match(page, /第一年 – 数据资产及分析框架落地：完成全域营销数据的端到端接入与串联/);
  assert.match(page, /第二年 – 高阶数据应用场景落地赋能精准投放：1）依托联邦计算合作实现一方\/三方数据协同/);
  assert.match(page, /第三年 - AI for BI 等智能分析场景/);
  assert.doesNotMatch(page, /第一年完成从品牌认知、兴趣互动到购买转化的全链路数据接入与可视化/);
  assert.match(page, /rolePlacement: "after-second-phase"/);
  assert.match(page, /PM\/BA Lead/);
  assert.match(page, /全球酒店集团｜CRM 会员运营战略与本地化 Campaign[\s\S]*咨询顾问/);
  assert.doesNotMatch(page, /全球汽车品牌｜CRM 用户流失诊断及召回策略/);
  assert.match(page, /头部豪华汽车品牌｜CRM 用户流失诊断及召回策略/);
  assert.doesNotMatch(page, /商品规划｜基于客户分群的数据建模与买货策略优化/);
  assert.match(page, /头部服装品牌｜基于客户分群的数据建模与买货策略优化/);
  assert.match(page, /10\+ 数据平台接入/);
  assert.match(page, /广告 ROI 提升 7%\+/);
  assert.match(page, /chelsea-portrait-v2\.jpg/);
  assert.doesNotMatch(page, /portrait-note/);
  assert.doesNotMatch(page, /以结果为责，以专业深耕价值/);
  assert.doesNotMatch(page, /id="education"/);
  assert.match(page, /联系方式：/);
  assert.match(page, /chuanshen5@163\.com/);
  assert.match(page, /130 8281 3052/);
  assert.match(page, /tel:\+8613082813052/);
  assert.match(page, /Shang Hai/);
  assert.match(page, /const alwaysOpenProjects = employer\.id === "pwc" \|\| employer\.id === "saic-gmac"/);
  assert.match(page, /const projectIsOpen = alwaysOpenProjects \|\| Boolean\(openProjects\[project\.id\]\)/);
  assert.match(page, /alwaysOpenProjects \? \(/);
  assert.match(page, /<div className="project-trigger static-project-trigger">/);
  assert.match(page, /!alwaysOpenProjects && <span aria-hidden="true">\{projectIsOpen \? "收起" : "展开"\}<\/span>/);
  assert.match(layout, /lang="zh-CN"/);
  assert.match(layout, /沈川 Chelsea \| 数字化转型与数据产品咨询顾问/);
  assert.match(layout, /og\.png/);
});

test("starter preview surface is not shipped", async () => {
  const [page, layout, css, packageJson] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
  ]);

  assert.doesNotMatch(page, /_sites-preview|SkeletonPreview|codex-preview/);
  assert.doesNotMatch(layout, /codex-preview|Starter Project/);
  assert.doesNotMatch(css, /\.site-header \{[^}]*border-bottom/);
  assert.doesNotMatch(css, /portrait-frame::before/);
  assert.match(css, /\.hero \{[^}]*min-height: 520px/);
  assert.match(css, /\.portrait-frame \{[^}]*justify-self: end/);
  assert.match(css, /\.portrait-frame \{[^}]*transform: translateX\(clamp\(-56px, -4vw, -28px\)\)/);
  assert.match(css, /\.portrait \{[^}]*width: clamp\(210px, 20vw, 250px\)/);
  assert.match(css, /\.portrait \{[^}]*height: clamp\(210px, 20vw, 250px\)/);
  assert.match(css, /\.portrait \{[^}]*border-radius: 50%/);
  assert.match(css, /\.portrait \{[^}]*box-shadow: none/);
  assert.match(css, /\.hero-belief \{[^}]*color: var\(--blue\)/);
  assert.match(css, /\.hero-subcopy \{[^}]*max-width: none/);
  assert.match(css, /\.profile h2 \{[^}]*color: var\(--ink\)/);
  assert.match(css, /\.profile h2 \{[^}]*font-size: clamp\(30px, 3\.75vw, 39px\)/);
  assert.match(css, /\.profile-subtitle \{[^}]*color: var\(--blue\)/);
  assert.match(css, /\.profile-subtitle \{[^}]*font-size: 13px/);
  assert.match(css, /\.static-project-trigger \{[^}]*cursor: default/);
  assert.match(css, /\.fact-grid span \{[^}]*font-size: 13px/);
  assert.match(css, /\.fact-grid strong \{[^}]*font-size: 20px/);
  assert.match(css, /\.section-heading h2, \.education h2 \{[^}]*font-size: clamp\(31px, 3\.75vw, 52px\)/);
  assert.match(css, /\.profile h2 \{[^}]*white-space: nowrap/);
  assert.match(css, /--charcoal: #101820/);
  assert.match(css, /\.capability-list \{[^}]*width: 100vw/);
  assert.match(css, /\.capability-list \{[^}]*margin-left: calc\(50% - 50vw\)/);
  assert.match(css, /\.capability-list \{[^}]*background: #fff/);
  assert.match(css, /\.capability-list article \{[^}]*min-height: 270px/);
  assert.match(css, /\.capability-list article \{[^}]*background: var\(--charcoal\)/);
  assert.match(css, /\.capability-list article \{[^}]*justify-content: center/);
  assert.match(css, /\.capability-list h3[^}]*color: #fff/);
  assert.match(css, /\.group-heading \{[^}]*background: var\(--charcoal\)/);
  assert.match(css, /\.group-heading h3[^}]*color: #fff/);
  assert.match(css, /\.group-heading h3[^}]*font-size: 13px/);
  assert.match(css, /\.project-trigger \{[^}]*padding: 16px 20px/);
  assert.match(css, /\.project-trigger \{[^}]*font-size: 13px/);
  assert.match(css, /\.project-detail \{[^}]*padding: 4px 20px 32px/);
  assert.match(css, /\.phase ul, \.project-bullets \{[^}]*padding-left: 36px/);
  assert.doesNotMatch(css, /\.project-list \{[^}]*border-left/);
  assert.doesNotMatch(css, /\.project-list \{[^}]*border-right/);
  assert.match(css, /prefers-reduced-motion/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
  assert.match(packageJson, /"test": "WRANGLER_LOG_PATH=\.wrangler\/wrangler\.log vinext build && node --test tests\/rendered-html\.test\.mjs"/);
  assert.doesNotMatch(packageJson, /"test": "npm run build/);
});
